# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, builds an image, performs a container image
# scan with Anchore's Syft tool, and uploads the results to the GitHub Dependency
# submission API.

# For more information on the Anchore sbom-action usage
# and parameters, see https://github.com/anchore/sbom-action. For more
# information about the Anchore SBOM tool, Syft, see
# https://github.com/anchore/syft

name: Upload BOM

on:
  release:
      types: [edited,released]

permissions:
  contents: write

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: write # required to upload to the Dependency submission API
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@main
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag localbuild/testimage:latest
    - name: Scan the image and upload dependency results
      uses: anchore/sbom-action@main
      with:
        path: "."
        artifact-name: src.spdx.json
        dependency-snapshot: true
        output-file: image
        format: spdx-json
        upload-release-assets: true
    - uses: anchore/sbom-action/publish-sbom@main
      with:
        sbom-artifact-match: "src.spdx.json$"
          
    - name: Scan SBOM
      uses: anchore/scan-action@main
      with:
        fail-build: false
        sbom: "src.spdx.json"
